### ISSUE TITLE
Make folders with icons more identifiable

### ISSUE THREAD

**Issue by gfxholo** [gfxholo/iconic#15]
Folder icons just replace the expand/collapse arrow at the moment. I think it looks clean, but you do lose the ability to tell it's a folder when they're collapsed. Some possible ideas:

- Leave arrows alone and insert icons ***next to them***
- Move arrows to the ***right edge*** after the text
- Show some sort of collapse indicator around icons

![#15](https://github.com/gfxholo/iconic/assets/157357541/4a7cc71c-e676-4f08-a37a-487bfeaf1402)

**Comment by hookxs** [comment]
Plus, it would be great if there were a setting "default icon for all folders" like there is for files. The way it is now, as far as I understand, all folders need to have their icons assigned manually. Otherwise I agree with the both arrow+icon suggestion
