### ISSUE TITLE
Nested Bookmark Groups are bugged

### ISSUE THREAD

**Issue by KhangHLe** [gfxholo/iconic#16]
If you add an icon to a group then drag it into another group, it stays until you make any changes any bookmarks, then it clears.

You can't add icon to nested bookmarks at all without needing to flatten it first.

**Comment by gfxholo** [comment]
Confirmed! Thanks Khang :]

![image](https://github.com/gfxholo/iconic/assets/157357541/54c79d79-0dc1-4267-af52-3ac2ffe722b1)
