### ISSUE TITLE
Duplicated right-click menu item

### ISSUE THREAD

**Issue by BolteDev** [gfxholo/iconic#23]
Just to confirm this was with no other icon plugins enabled.
![image](https://github.com/user-attachments/assets/2b686fcc-de0e-4819-a102-d81a6dc30b1c)

Iconic version 1.0.13 using Obsidian 1.6.7 on Desktop

**Comment by gfxholo** [comment]
Thanks Bolte, I've seen this happen randomly in recent patches too. Should be easy to fix once I find what's double-tapping the menu item code.
