### ISSUE TITLE
Request: Zipped release for manual install

### ISSUE THREAD

**Issue by 1ku1** [gfxholo/iconic#25]
In order to install the plugin manually, you have to download the three files individually, then create a folder and rename it with the plugin id and put these files in it.

I know these files are needed for automatic installation to work, but it would be much easier for the user to be able to **download a zipped file also** from the releases tab in the following configuration:

```
plugin-id-{v}.zip
    plugin-id\
        main.js
        manifest.json
        styles.css
```

This way we can just extract the zip file in the plugin folder. Thank you.

**Comment by gfxholo** [comment]
Hi @1ku1! I totally see the benefit of this, but it's a pretty small edge case to support when we already have the official community browser, and alternative updaters like [BRAT](https://github.com/TfTHacker/obsidian42-brat) and [VARE](https://github.com/4Source/vare-obsidian-plugin) as well. I'm guessing the average user won't be trying a manual installation unless they already know exactly what they're doing.

Are you doing something unique with the releases, like re-hosting them on a blog for example?

**Comment by 1ku1** [comment]
> Are you doing something unique with the releases, like re-hosting them on a blog for example?

No, nothing like that. We just have a firewall policy.

**Comment by gfxholo** [comment]
Okay! Checking out your recent pull requests, I found four good examples of this being done with no problems on the Obsidian end:
- [Settings Search](https://github.com/javalent/settings-search/blob/main/.github/workflows/release-please.yml)
- [Better Command Palette](https://github.com/AlexBieg/obsidian-better-command-palette/blob/master/.github/workflows/release.yml)
- [Settings Profiles](https://github.com/4Source/settings-profiles-obsidian-plugin/blob/master/.github/workflows/release.yml)
- [Linter](https://github.com/platers/obsidian-linter/blob/master/.github/workflows/release.yml)

I should be able to wire this into the next release :)

**Comment by 1ku1** [comment]
Thank you!
