### ISSUE TITLE
Question on feature usage

### ISSUE THREAD

**Issue by agoldenlife** [gfxholo/iconic#26]
You mention that this plugin can do all this more than iconize:

Download and import icon packs
Use Twitter-style emojis
Type icons directly into your notes
Show icons beside links
Show icons beside note titles
Obey icon and icon Color properties
Auto-set icons based on filename rules
Customize icon size & margins

Other than click the menu in the upper right or right clicking a folder or file. That is only 2 features that I can get to work.  I don't see any way to do any of the above mentioned items and no instructions either.  I am just trying to get an icon in my note.  How is that done?

Thanks.

**Comment by gfxholo** [comment]
Sorry for the confusion! That section of the readme is a feature comparison with Iconize, and the bullet points you've listed are the features this plugin *doesn't* support.

See: [How is this plugin different from Iconize?](https://github.com/gfxholo/iconic?tab=readme-ov-file#how-is-this-plugin-different-from-iconize)

**Comment by agoldenlife** [comment]
Ah, sorry about that. I should have caught that.  Thanks for responding!
