### ISSUE TITLE
Obsidian sync not reliably syncing icons

### ISSUE THREAD

**Issue by cyanomys** [gfxholo/iconic#31]
Devices are mac/iOS. For some reason it seems to sync some but not others.

**Comment by gfxholo** [comment]
Hiya, I haven't noticed any issues with the icon syncing lately. Can you let me know if:
- Certain icons always fail to sync, or is it just random?
- Reloading the app on the "receiving" device after syncing is finished makes a difference?
- You have any excluded folders or filetypes in your Sync settings?

**Comment by cyanomys** [comment]
1. Nope, seems kinda random
2. Nope.
3. OHH turns out I somehow had installed community plugins sync disabled on just my desktop but not my mobile devices. That explains some of them but not all of them *seeming* to sync. Issue fixed!
