### ISSUE TITLE
Collision of 'Folder Notes' plugin with 'Minimal folder icons' setting

### ISSUE THREAD

**Issue by JoeKays** [gfxholo/iconic#34]
Hi,

would it be possible to add a compatibility option so that the 'Minimal folder icons' setting doesn't cause issues with the 'Folder Notes' plugin?

When the 'Folder Notes' plugin is enabled, clicking on the name of a folder opens it's folder note without expanding the folder. Thus, the only/primary way to expand a folder is by clicking on the arrow, which is hidden by the 'Minimal folder icons' setting.

Instead, it would be great to be able to expand a folder by clicking on it's icon. Currently, this opens the 'Change icon' dialog (which can  already be accessed by right-clicking). Could you add an option for this?

Thank you!

**Comment by gfxholo** [comment]
Hi Joe! Does switching this setting off make any difference?

![#34](https://github.com/user-attachments/assets/dcedafd0-7bb6-4240-bf1a-ddd6c6a145cb)

If not, let me know exactly which folder note plugin you use and I'll take a look!

**Comment by JoeKays** [comment]
@gfxholo Thanks, of course this fixes it, sorry!

Maybe the wording could be improved a bit here, e.g. 'Click an icon to either open the icon picker or open/expand the file/folder', something like that.

**Comment by gfxholo** [comment]
Noted! That setting controls all of the sidebar / property / main tab icons, so it's hard to cram that into one description haha. I'm glad it fixes your issue 🙌
