### ISSUE TITLE
No icon pack import?

### ISSUE THREAD

**Issue by Minus10Celcius** [gfxholo/iconic#35]
~~In the README, theres a mention of "icon packs" but I don't see it anywhere in the plugin settings?~~

IM SO DUMB IT SAID ICONIZE NOT ICONIC SU8YGFTYUJNB

**Comment by gfxholo** [comment]
It's okay, you're not dumb! That part of the readme is easy to misread honestly. I'll rewrite it when I push the next update so nobody else gets confused 💚
