### ISSUE TITLE
Plugin is resetting Ribbon Menu config

### ISSUE THREAD

**Issue by KhangHLe** [gfxholo/iconic#9]
This plugin is overriding the Ribbon Menu config and shows all hidden menu items.

Duplications:
1. Disable Plugin
2. Hide items from Ribbon Menu
3. Re-enable plugin
4. Items on Ribbon are showing again

**Comment by gfxholo** [comment]
Thanks for reporting this! I want to say nice catch, but I can't reproduce this bug myself.

Can you try following those steps with no other plugins enabled, and let me know if it still happens? I think there's some other ingredient in this recipe...

**Comment by KhangHLe** [comment]
I disabled every plugin, I'm using the default theme, I was still able to duplicate by enabling this plugin, this happens on other PCs I synced to as well, see attached video.

https://github.com/gfxholo/iconic/assets/8367424/1574a616-455c-486e-b425-ea9bccf6cc25

**Comment by gfxholo** [comment]
Whoa yeah, that's definitely a bug. It suddenly started happening to me now too. I'll focus on getting this fixed for the next patch. Thanks for recording such a clean example. 🤙
